import { Sidebar } from "@/components/sidebar";
import { PlanStoreProvider } from "@/stores/plan-store-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/react-query-client-provider";
import { SIDEBAR_CONFIGS } from "@/constants/sidebar-constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <Toaster />
          <Sidebar.Button />
          <Sidebar>
            <Sidebar.Items>
              {SIDEBAR_CONFIGS.map((config) => (
                <Sidebar.Item
                  key={config.id}
                  href={config.href}
                  label={config.label}
                  icon={config.icon}
                />
              ))}
            </Sidebar.Items>
          </Sidebar>
          <div className="min-h-screen p-4 sm:ml-64">{children}</div>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
